-- Official RSS links verified 2026-09-04; see docs/news-categories.md.
return {
    { id = "vietnamplus", title = "VietnamPlus", lang = "vi", region = "vietnam",
      base_url = "", categories = {
        { "Trang chủ", "https://www.vietnamplus.vn/rss/home.rss" },
        { "Chính trị", "https://www.vietnamplus.vn/rss/chinhtri-291.rss" },
        { "Thế giới", "https://www.vietnamplus.vn/rss/thegioi-209.rss" },
        { "ASEAN", "https://www.vietnamplus.vn/rss/thegioi/asean-356.rss" },
        { "Châu Á-TBD", "https://www.vietnamplus.vn/rss/thegioi/chaua-tbd-352.rss" },
        { "Trung Đông", "https://www.vietnamplus.vn/rss/thegioi/trungdong-230.rss" },
        { "Châu Âu", "https://www.vietnamplus.vn/rss/thegioi/chauau-354.rss" },
        { "Châu Mỹ", "https://www.vietnamplus.vn/rss/thegioi/chaumy-355.rss" },
        { "Châu Phi", "https://www.vietnamplus.vn/rss/thegioi/chauphi-357.rss" },
        { "Kinh tế", "https://www.vietnamplus.vn/rss/kinhte-311.rss" },
        { "Kinh doanh", "https://www.vietnamplus.vn/rss/kinhte/kinhdoanh-342.rss" },
        { "Tài chính", "https://www.vietnamplus.vn/rss/kinhte/taichinh-343.rss" },
        { "Tín dụng nông thôn", "https://www.vietnamplus.vn/rss/kinhte/tindung-385.rss" },
        { "Chứng khoán", "https://www.vietnamplus.vn/rss/kinhte/chungkhoan-344.rss" },
        { "Bất động sản", "https://www.vietnamplus.vn/rss/kinhte/batdongsan-372.rss" },
        { "Doanh nghiệp", "https://www.vietnamplus.vn/rss/kinhte/doanhnghiep-345.rss" },
        { "Xã hội", "https://www.vietnamplus.vn/rss/xahoi-314.rss" },
        { "Giáo dục", "https://www.vietnamplus.vn/rss/xahoi/giaoduc-316.rss" },
        { "Y tế", "https://www.vietnamplus.vn/rss/xahoi/yte-325.rss" },
        { "Pháp luật", "https://www.vietnamplus.vn/rss/xahoi/phapluat-327.rss" },
        { "Giao thông", "https://www.vietnamplus.vn/rss/xahoi/giaothong-358.rss" },
        { "Người Việt bốn phương", "https://www.vietnamplus.vn/rss/xahoi/vietkieu-373.rss" },
        { "Đời sống", "https://www.vietnamplus.vn/rss/doisong-320.rss" },
        { "Phong cách", "https://www.vietnamplus.vn/rss/doisong/phongcach-365.rss" },
        { "Sức khỏe", "https://www.vietnamplus.vn/rss/doisong/suckhoe-367.rss" },
        { "Làm đẹp", "https://www.vietnamplus.vn/rss/doisong/lamdep-366.rss" },
        { "Ẩm thực", "https://www.vietnamplus.vn/rss/doisong/amthuc-351.rss" },
        { "Anh hùng nhỏ", "https://www.vietnamplus.vn/rss/doisong/littleheroes-425.rss" },
        { "Văn hóa", "https://www.vietnamplus.vn/rss/vanhoa-215.rss" },
        { "Điện ảnh", "https://www.vietnamplus.vn/rss/vanhoa/dienanh-293.rss" },
        { "Âm nhạc", "https://www.vietnamplus.vn/rss/vanhoa/amnhac-321.rss" },
        { "Thời trang", "https://www.vietnamplus.vn/rss/vanhoa/thoitrang-359.rss" },
        { "Điểm Nhạc-Phim-Sách", "https://www.vietnamplus.vn/rss/vanhoa/nhac-phim-sach-381.rss" },
        { "Truyền thông", "https://www.vietnamplus.vn/rss/vanhoa/truyenthong-391.rss" },
        { "Thể thao", "https://www.vietnamplus.vn/rss/thethao-214.rss" },
        { "Bóng đá", "https://www.vietnamplus.vn/rss/thethao/bongda-368.rss" },
        { "Quần vợt", "https://www.vietnamplus.vn/rss/thethao/quanvot-369.rss" },
        { "Khoa học", "https://www.vietnamplus.vn/rss/khoahoc-213.rss" },
        { "Khoa học ứng dụng", "https://www.vietnamplus.vn/rss/khoahoc/ungdung-371.rss" },
        { "Công nghệ", "https://www.vietnamplus.vn/rss/congnghe-212.rss" },
        { "Sản phẩm mới", "https://www.vietnamplus.vn/rss/congnghe/sanphammoi-275.rss" },
        { "Ôtô-Xe máy", "https://www.vietnamplus.vn/rss/otoxemay-364.rss" },
        { "Môi trường", "https://www.vietnamplus.vn/rss/moitruong-270.rss" },
        { "Du lịch", "https://www.vietnamplus.vn/rss/dulich-237.rss" },
        { "Điểm đến", "https://www.vietnamplus.vn/rss/dulich/diemden-284.rss" },
        { "Lễ hội", "https://www.vietnamplus.vn/rss/dulich/lehoi-285.rss" },
        { "Khách sạn/Resort", "https://www.vietnamplus.vn/rss/dulich/khachsanresort-360.rss" },
        { "Tour mới", "https://www.vietnamplus.vn/rss/dulich/tourmoi-361.rss" },
        { "Thị trường", "https://www.vietnamplus.vn/rss/tinthitruong-218.rss" },
        { "Chuyện lạ", "https://www.vietnamplus.vn/rss/chuyenla-329.rss" },
        { "Special+", "https://www.vietnamplus.vn/rss/special-plus-450.rss" },
        { "RapNewsPlus", "https://www.vietnamplus.vn/rss/rapnewsplus-390.rss" },
        { "News Game", "https://www.vietnamplus.vn/rss/newsgame-401.rss" },
        { "Game thời sự", "https://www.vietnamplus.vn/rss/gamenews-402.rss" },
        { "Game giải trí", "https://www.vietnamplus.vn/rss/gamefun-403.rss" },
        { "Game kiến thức", "https://www.vietnamplus.vn/rss/gameeducation-404.rss" },
        { "Thăm dò ý kiến", "https://www.vietnamplus.vn/rss/gamepoll-405.rss" },
        { "Nội dung thu phí", "https://www.vietnamplus.vn/rss/thuphi-424.rss" },
    } },
    { id = "baotintuc", title = "Báo Tin tức", lang = "vi", region = "vietnam",
      base_url = "", categories = {
        { "Trang chủ", "https://baotintuc.vn/tin-moi-nhat.rss" },
        { "Thời sự", "https://baotintuc.vn/thoi-su.rss" },
        { "Thế giới", "https://baotintuc.vn/the-gioi.rss" },
        { "Kinh tế", "https://baotintuc.vn/kinh-te.rss" },
        { "Xã hội", "https://baotintuc.vn/xa-hoi.rss" },
        { "Pháp luật", "https://baotintuc.vn/phap-luat.rss" },
        { "Văn hóa", "https://baotintuc.vn/van-hoa.rss" },
        { "Giáo dục", "https://baotintuc.vn/giao-duc.rss" },
        { "Thể thao", "https://baotintuc.vn/the-thao.rss" },
        { "Hồ sơ", "https://baotintuc.vn/ho-so.rss" },
        { "Quân sự", "https://baotintuc.vn/quan-su.rss" },
        { "Khoa học - Công nghệ", "https://baotintuc.vn/khoa-hoc-cong-nghe.rss" },
        { "Biển đảo", "https://baotintuc.vn/bien-dao-viet-nam.rss" },
        { "Y tế", "https://baotintuc.vn/suc-khoe.rss" },
        { "Địa phương", "https://baotintuc.vn/dia-phuong.rss" },
        { "Video", "https://baotintuc.vn/video.rss" },
        { "Góc nhìn", "https://baotintuc.vn/goc-nhin.rss" },
        { "Ảnh", "https://baotintuc.vn/anh.rss" },
        { "Infographics", "https://baotintuc.vn/infographics.rss" },
        { "Đặc biệt", "https://baotintuc.vn/emagazine.rss" },
        { "Bạn đọc", "https://baotintuc.vn/ban-doc.rss" },
        { "Dân tộc miền núi", "https://baotintuc.vn/giai-ma-muon-mat.rss" },
        { "Ảnh 360", "https://baotintuc.vn/anh-360.rss" },
    } },
    { id = "nhandan", title = "Nhân Dân", lang = "vi", region = "vietnam",
      base_url = "", categories = {
        { "Trang chủ", "https://nhandan.vn/rss/home.rss" },
        { "Chính trị", "https://nhandan.vn/rss/chinhtri-1171.rss" },
        { "Xã luận", "https://nhandan.vn/rss/xa-luan-1176.rss" },
        { "Bình luận - Phê phán", "https://nhandan.vn/rss/binh-luan-phe-phan-1180.rss" },
        { "Xây dựng Đảng", "https://nhandan.vn/rss/xay-dung-dang-1179.rss" },
        { "Kinh tế", "https://nhandan.vn/rss/kinhte-1185.rss" },
        { "Tài chính – Chứng khoán", "https://nhandan.vn/rss/chungkhoan-1191.rss" },
        { "Thông tin hàng hóa", "https://nhandan.vn/rss/thong-tin-hang-hoa-1203.rss" },
        { "Văn hóa", "https://nhandan.vn/rss/vanhoa-1251.rss" },
        { "Xã hội", "https://nhandan.vn/rss/xahoi-1211.rss" },
        { "BHXH và cuộc sống", "https://nhandan.vn/rss/bhxh-va-cuoc-song-1222.rss" },
        { "Người tốt việc tốt", "https://nhandan.vn/rss/nguoi-tot-viec-tot-1319.rss" },
        { "Pháp luật", "https://nhandan.vn/rss/phapluat-1287.rss" },
        { "Du lịch", "https://nhandan.vn/rss/du-lich-1257.rss" },
        { "Thế giới", "https://nhandan.vn/rss/thegioi-1231.rss" },
        { "Bình luận quốc tế", "https://nhandan.vn/rss/binh-luan-quoc-te-1236.rss" },
        { "ASEAN", "https://nhandan.vn/rss/asean-704471.rss" },
        { "Châu Phi", "https://nhandan.vn/rss/chau-phi-704476.rss" },
        { "Châu Mỹ", "https://nhandan.vn/rss/chau-my-704475.rss" },
        { "Châu Âu", "https://nhandan.vn/rss/chau-au-704474.rss" },
        { "Trung Đông", "https://nhandan.vn/rss/trung-dong-704473.rss" },
        { "Châu Á-TBD", "https://nhandan.vn/rss/chau-a-tbd-704472.rss" },
        { "Thể thao", "https://nhandan.vn/rss/thethao-1224.rss" },
        { "Giáo dục", "https://nhandan.vn/rss/giaoduc-1303.rss" },
        { "Y tế", "https://nhandan.vn/rss/y-te-1309.rss" },
        { "Góc tư vấn", "https://nhandan.vn/rss/goc-tu-van-1311.rss" },
        { "Khoa học - Công nghệ", "https://nhandan.vn/rss/khoahoc-congnghe-1292.rss" },
        { "Phòng, chống tội phạm công nghệ cao", "https://nhandan.vn/rss/phong-chong-toi-pham-cong-nghe-cao-2025-704717.rss" },
        { "Môi trường", "https://nhandan.vn/rss/moi-truong-1296.rss" },
        { "Bạn đọc", "https://nhandan.vn/rss/bandoc-1315.rss" },
        { "Đường dây nóng", "https://nhandan.vn/rss/duong-day-nong-1316.rss" },
        { "Điều tra qua thư bạn đọc", "https://nhandan.vn/rss/dieu-tra-qua-thu-ban-doc-1317.rss" },
        { "Kiểm chứng thông tin", "https://nhandan.vn/rss/factcheck-658978.rss" },
        { "Tri thức chuyên sâu", "https://nhandan.vn/rss/tri-thuc-chuyen-sau-704477.rss" },
        { "54 dân tộc Việt Nam", "https://nhandan.vn/rss/54-dan-toc-704489.rss" },
        { "Chương trình OCOP - Mỗi xã một sản phẩm", "https://nhandan.vn/rss/ocop-704555.rss" },
    } },
    { id = "sggp", title = "Sài Gòn Giải Phóng", lang = "vi", region = "vietnam",
      base_url = "", categories = {
        { "Trang chủ", "https://www.sggp.org.vn/rss/home.rss" },
        { "Chính trị", "https://www.sggp.org.vn/rss/chinhtri-24.rss" },
        { "Quốc phòng – an ninh", "https://www.sggp.org.vn/rss/quoc-phong-an-ninh-518.rss" },
        { "Nhân sự", "https://www.sggp.org.vn/rss/chinhtri/nhansumoi-364.rss" },
        { "Xây dựng Đảng", "https://www.sggp.org.vn/rss/xaydungdang-204.rss" },
        { "Đối ngoại", "https://www.sggp.org.vn/rss/chinhtri-doingoai-196.rss" },
        { "Xã hội", "https://www.sggp.org.vn/rss/xahoi-199.rss" },
        { "Sự kiện & Bình luận", "https://www.sggp.org.vn/rss/theodongthoisu-144.rss" },
        { "Cải cách hành chính", "https://www.sggp.org.vn/rss/sapxepcacdonvihanhchinh-558.rss" },
        { "Đô thị", "https://www.sggp.org.vn/rss/xahoi-giaothong-3.rss" },
        { "Giao thông", "https://www.sggp.org.vn/rss/xahoi-gt-525.rss" },
        { "Tuổi trẻ cuộc sống", "https://www.sggp.org.vn/rss/xahoi-tuoitrecuocsong-520.rss" },
        { "Bút Sài Gòn", "https://www.sggp.org.vn/rss/xahoi/butsaigon-217.rss" },
        { "Tin buồn", "https://www.sggp.org.vn/rss/xahoi/tinbuon-219.rss" },
        { "Môi trường", "https://www.sggp.org.vn/rss/xahoi-moitruong-52.rss" },
        { "Pháp luật", "https://www.sggp.org.vn/rss/phapluat-112.rss" },
        { "An ninh - trật tự", "https://www.sggp.org.vn/rss/anninhtrattu-2.rss" },
        { "Câu chuyện Pháp luật", "https://www.sggp.org.vn/rss/tuvanphapluat-440.rss" },
        { "Kinh tế", "https://www.sggp.org.vn/rss/kinhte-89.rss" },
        { "Thị trường", "https://www.sggp.org.vn/rss/thitruongkt-150.rss" },
        { "Địa ốc", "https://www.sggp.org.vn/rss/xaydungdiaoc-205.rss" },
        { "Tài chính- Chứng khoán", "https://www.sggp.org.vn/rss/kinhte-taichinhchuungkhoan-44.rss" },
        { "Du lịch", "https://www.sggp.org.vn/rss/dulichkhampha-65.rss" },
        { "Đầu tư", "https://www.sggp.org.vn/rss/dautukt-37.rss" },
        { "Doanh nghiệp - Doanh nhân", "https://www.sggp.org.vn/rss/kinhte-doanhnghiepdoanhnhan-524.rss" },
        { "Chuyển động kinh tế & Đời sống 24H", "https://www.sggp.org.vn/rss/kinhtedoisong24h-421.rss" },
        { "Đa phương tiện", "https://www.sggp.org.vn/rss/daphuongtien-494.rss" },
        { "Thế giới", "https://www.sggp.org.vn/rss/thegioi-143.rss" },
        { "Chính trường thế giới", "https://www.sggp.org.vn/rss/chinhtruongthegioi-26.rss" },
        { "Hồ sơ - tư liệu", "https://www.sggp.org.vn/rss/hosotulieu-85.rss" },
        { "Chuyện đó đây", "https://www.sggp.org.vn/rss/thegioi/doisonghanhtinh-251.rss" },
        { "Giáo dục", "https://www.sggp.org.vn/rss/giaoduc-71.rss" },
        { "Giáo dục học đường", "https://www.sggp.org.vn/rss/giaoduc/gdhd-583.rss" },
        { "Hướng nghiệp - tuyển sinh", "https://www.sggp.org.vn/rss/giaoduc/tuyensinhdhoccdang-339.rss" },
        { "Giáo dục hội nhập", "https://www.sggp.org.vn/rss/giaoduc/gdhn-329.rss" },
        { "Sống khỏe", "https://www.sggp.org.vn/rss/ytesuckhoe-212.rss" },
        { "An toàn thực phẩm", "https://www.sggp.org.vn/rss/ytesuckhoe-antoanthucpham-216.rss" },
        { "Sức khỏe cộng đồng", "https://www.sggp.org.vn/rss/ytesuckhoe/suckhoecongdong-432.rss" },
        { "Văn hóa", "https://www.sggp.org.vn/rss/vanhoavannghe-186.rss" },
        { "Nhịp sống", "https://www.sggp.org.vn/rss/nhip-song-519.rss" },
        { "Nhân vật", "https://www.sggp.org.vn/rss/vanhoagiaitri-nhanvat-523.rss" },
        { "Giải trí", "https://www.sggp.org.vn/rss/dienanh-42.rss" },
        { "Sách", "https://www.sggp.org.vn/rss/vanhoagiaitri-sach-232.rss" },
        { "Bạn đọc", "https://www.sggp.org.vn/rss/nhipcaubandoc-107.rss" },
        { "Ý kiến bạn đọc", "https://www.sggp.org.vn/rss/nhipcaubandoc-ykienbandoc-318.rss" },
        { "Diễn đàn - Thảo luận", "https://www.sggp.org.vn/rss/nhipcaubandoc-diendan-thaoluan-526.rss" },
        { "Cơ quan trả lời", "https://www.sggp.org.vn/rss/nhipcaubandoc/coquantraloi-319.rss" },
        { "Lao động - An sinh", "https://www.sggp.org.vn/rss/laodongansinh-595.rss" },
        { "An sinh xã hội", "https://www.sggp.org.vn/rss/ansinhxahoi-603.rss" },
        { "Công đoàn - Công nhân", "https://www.sggp.org.vn/rss/congdoancongnhan-602.rss" },
        { "Nguồn nhân lực", "https://www.sggp.org.vn/rss/nguonnhanluc-601.rss" },
        { "Lao động - Việc làm", "https://www.sggp.org.vn/rss/laodongansinhvieclam-600.rss" },
        { "Phụ nữ", "https://www.sggp.org.vn/rss/phunu-594.rss" },
        { "Nhịp sống hội", "https://www.sggp.org.vn/rss/nhipsonghoi-599.rss" },
        { "Tình và Lý", "https://www.sggp.org.vn/rss/tinhvaly-598.rss" },
        { "Dòng chảy cuộc sống", "https://www.sggp.org.vn/rss/dongchaycuocsong-597.rss" },
        { "Mái ấm", "https://www.sggp.org.vn/rss/maiam-596.rss" },
        { "Khoa học công nghệ", "https://www.sggp.org.vn/rss/khoahoc-congnghe-90.rss" },
    } },
}
