-- Official RSS links verified 2026-09-04; see docs/news-categories.md.
return {
    { id = "tienphong", title = "Tiền Phong", lang = "vi", region = "vietnam",
      base_url = "", categories = {
        { "Trang chủ", "https://tienphong.vn/rss/home.rss" },
        { "Xã hội", "https://tienphong.vn/rss/xa-hoi-2.rss" },
        { "Chính trị", "https://tienphong.vn/rss/chinh-tri-308.rss" },
        { "Tin tức", "https://tienphong.vn/rss/xa-hoi-tin-tuc-104.rss" },
        { "Phóng sự", "https://tienphong.vn/rss/xa-hoi-phong-su-13.rss" },
        { "Kinh tế", "https://tienphong.vn/rss/kinh-te-3.rss" },
        { "Kinh tế / Thị trường", "https://tienphong.vn/rss/kinh-te-thi-truong-24.rss" },
        { "Doanh nghiệp", "https://tienphong.vn/rss/doanh-nghiep-22.rss" },
        { "Kinh tế / Đầu tư", "https://tienphong.vn/rss/dau-tu-165.rss" },
        { "Tài chính - Chứng khoán", "https://tienphong.vn/rss/tai-chinh-chung-khoan-105.rss" },
        { "Giảm nghèo bền vững", "https://tienphong.vn/rss/giam-ngheo-ben-vung-413.rss" },
        { "Sóng xanh", "https://tienphong.vn/rss/song-xanh-441.rss" },
        { "Di chuyển xanh", "https://tienphong.vn/rss/di-chuyen-xanh-442.rss" },
        { "Net zero", "https://tienphong.vn/rss/netzero-443.rss" },
        { "Sóng xanh / Đầu tư", "https://tienphong.vn/rss/song-xanh-dau-tu-444.rss" },
        { "Lifestyle", "https://tienphong.vn/rss/lifestyle-445.rss" },
        { "Xanh 4.0", "https://tienphong.vn/rss/xanh-4-0-446.rss" },
        { "Địa ốc", "https://tienphong.vn/rss/dia-oc-166.rss" },
        { "Đô thị - Dự án", "https://tienphong.vn/rss/do-thi-du-an-269.rss" },
        { "Thị trường - Doanh nghiệp", "https://tienphong.vn/rss/thi-truong-doanh-nghiep-270.rss" },
        { "Nhà đẹp - Kiến trúc", "https://tienphong.vn/rss/nha-dep-kien-truc-271.rss" },
        { "Chuyên gia - Tư vấn", "https://tienphong.vn/rss/chuyen-gia-tu-van-272.rss" },
        { "Media Địa ốc", "https://tienphong.vn/rss/media-dia-oc-169.rss" },
        { "Sức khỏe", "https://tienphong.vn/rss/suc-khoe-210.rss" },
        { "Y khoa", "https://tienphong.vn/rss/y-khoa-304.rss" },
        { "Thuốc tốt", "https://tienphong.vn/rss/thuoc-tot-305.rss" },
        { "Khỏe đẹp", "https://tienphong.vn/rss/khoe-dep-306.rss" },
        { "Giới tính", "https://tienphong.vn/rss/suc-khoe-gioi-tinh-144.rss" },
        { "Mẹ và bé", "https://tienphong.vn/rss/me-va-be-447.rss" },
        { "Phòng chống ung thư", "https://tienphong.vn/rss/phong-chong-ung-thu-448.rss" },
        { "Thế giới", "https://tienphong.vn/rss/the-gioi-5.rss" },
        { "Phân tích - Bình luận", "https://tienphong.vn/rss/the-gioi-phan-tich-binh-luan-31.rss" },
        { "Chuyện lạ", "https://tienphong.vn/rss/chuyen-la-32.rss" },
        { "Giới trẻ", "https://tienphong.vn/rss/gioi-tre-4.rss" },
        { "Nhịp sống", "https://tienphong.vn/rss/gioi-tre-nhip-song-27.rss" },
        { "Cộng đồng mạng", "https://tienphong.vn/rss/cong-dong-mang-26.rss" },
        { "Pháp luật", "https://tienphong.vn/rss/phap-luat-12.rss" },
        { "Bản tin 113", "https://tienphong.vn/rss/ban-tin-113-231.rss" },
        { "Pháp đình", "https://tienphong.vn/rss/phap-luat-chuyen-toa-173.rss" },
        { "Thể thao", "https://tienphong.vn/rss/the-thao-11.rss" },
        { "Bóng đá", "https://tienphong.vn/rss/the-thao-bong-da-49.rss" },
        { "Hậu trường thể thao", "https://tienphong.vn/rss/the-thao-hau-truong-111.rss" },
        { "Golf", "https://tienphong.vn/rss/the-thao-golf-280.rss" },
        { "HIGHLIGHTS", "https://tienphong.vn/rss/video-the-thao-425.rss" },
        { "Người lính", "https://tienphong.vn/rss/hanh-trang-nguoi-linh-182.rss" },
        { "Xe", "https://tienphong.vn/rss/xe-113.rss" },
        { "Thị trường xe", "https://tienphong.vn/rss/thi-truong-xe-276.rss" },
        { "Đánh giá xe", "https://tienphong.vn/rss/danh-gia-xe-277.rss" },
        { "Cộng đồng xe", "https://tienphong.vn/rss/cong-dong-xe-278.rss" },
        { "Tư vấn", "https://tienphong.vn/rss/xe-tu-van-279.rss" },
        { "Văn hóa", "https://tienphong.vn/rss/van-hoa-7.rss" },
        { "Chuyển động văn hóa", "https://tienphong.vn/rss/chuyen-dong-van-hoa-264.rss" },
        { "Sách", "https://tienphong.vn/rss/sach-429.rss" },
        { "Góc nhìn", "https://tienphong.vn/rss/goc-nhin-262.rss" },
        { "Giải trí", "https://tienphong.vn/rss/giai-tri-36.rss" },
        { "Phim ảnh", "https://tienphong.vn/rss/phim-anh-35.rss" },
        { "Hậu trường sao", "https://tienphong.vn/rss/giai-tri-hau-truong-168.rss" },
        { "Âm nhạc", "https://tienphong.vn/rss/am-nhac-153.rss" },
        { "Thời trang - Làm đẹp", "https://tienphong.vn/rss/thoi-trang-lam-dep-213.rss" },
        { "Giáo dục", "https://tienphong.vn/rss/giao-duc-71.rss" },
        { "Cổng trường", "https://tienphong.vn/rss/cong-truong-310.rss" },
        { "Tuyển sinh", "https://tienphong.vn/rss/tuyen-sinh2011-163.rss" },
        { "Du học", "https://tienphong.vn/rss/giao-duc-du-hoc-40.rss" },
        { "Khoa học", "https://tienphong.vn/rss/khoa-hoc-45.rss" },
        { "Hoa hậu", "https://tienphong.vn/rss/hoa-hau-253.rss" },
        { "Tin tức trong nước", "https://tienphong.vn/rss/hh-tin-tuc-trong-nuoc-255.rss" },
        { "Hoa hậu Việt Nam", "https://tienphong.vn/rss/hoa-hau-viet-nam-257.rss" },
        { "Quốc tế", "https://tienphong.vn/rss/quoc-te-265.rss" },
        { "Bạn đọc", "https://tienphong.vn/rss/ban-doc-15.rss" },
        { "Điều tra", "https://tienphong.vn/rss/ban-doc-dieu-tra-300.rss" },
        { "Diễn đàn", "https://tienphong.vn/rss/ban-doc-dien-dan-301.rss" },
        { "Hồi âm", "https://tienphong.vn/rss/ban-doc-hoi-am-302.rss" },
        { "Nhân ái", "https://tienphong.vn/rss/ban-doc-nhan-ai-303.rss" },
        { "Video", "https://tienphong.vn/rss/video-clip-115.rss" },
        { "Thời sự", "https://tienphong.vn/rss/thoi-su-421.rss" },
        { "Showbiz-TV", "https://tienphong.vn/rss/showbiz-tv-422.rss" },
        { "Thời tiết", "https://tienphong.vn/rss/thoi-tiet-423.rss" },
        { "Video / Thị trường", "https://tienphong.vn/rss/video-thi-truong-424.rss" },
        { "Quân sự", "https://tienphong.vn/rss/quan-su-426.rss" },
        { "Mutex", "https://tienphong.vn/rss/mutex-427.rss" },
        { "Tôi nghĩ", "https://tienphong.vn/rss/toi-nghi-273.rss" },
        { "Nhật báo", "https://tienphong.vn/rss/nhat-bao-433.rss" },
        { "Hàng không - Du lịch", "https://tienphong.vn/rss/hang-khong-du-lich-220.rss" },
        { "Hành trình", "https://tienphong.vn/rss/hanh-trinh-434.rss" },
        { "Mở vali", "https://tienphong.vn/rss/mo-vali-435.rss" },
        { "Vivu", "https://tienphong.vn/rss/vi-vu-436.rss" },
        { "Khoảnh khắc", "https://tienphong.vn/rss/khoanh-khac-437.rss" },
        { "Đối thoại", "https://tienphong.vn/rss/doi-thoai-438.rss" },
        { "Nhịp sống Thủ đô", "https://tienphong.vn/rss/nhip-song-thu-do-242.rss" },
        { "Đời sống", "https://tienphong.vn/rss/nstd-doi-song-243.rss" },
        { "Giao thông - Đô thị", "https://tienphong.vn/rss/nstd-giao-thong-do-thi-244.rss" },
        { "Nhịp sống Thủ đô / Đầu tư", "https://tienphong.vn/rss/nstd-dau-tu-245.rss" },
        { "Môi trường", "https://tienphong.vn/rss/nstd-moi-truong-313.rss" },
        { "Nhịp sống phương Nam", "https://tienphong.vn/rss/nhip-song-phuong-nam-408.rss" },
        { "Chuyển động 24h", "https://tienphong.vn/rss/chuyen-dong-24h-409.rss" },
        { "Giao thông – Đô thị", "https://tienphong.vn/rss/giao-thong-do-thi-410.rss" },
        { "Kinh tế - Thị trường", "https://tienphong.vn/rss/kinh-te--thi-truong-411.rss" },
        { "Media", "https://tienphong.vn/rss/media-412.rss" },
        { "Tết Việt", "https://tienphong.vn/rss/tet-viet-416.rss" },
        { "Đính chính", "https://tienphong.vn/rss/dinh-chinh-476.rss" },
    } },
}
