-- Official publisher feeds checked 2026-09-04. Unavailable URLs are documented, not guessed.
return {
    { id = "bbc", title = "BBC News", lang = "en", region = "world",
      base_url = "", filter_element = "article", categories = {
        { "Top Stories", "https://feeds.bbci.co.uk/news/rss.xml" },
        { "World", "https://feeds.bbci.co.uk/news/world/rss.xml" },
        { "UK", "https://feeds.bbci.co.uk/news/uk/rss.xml" },
        { "Business", "https://feeds.bbci.co.uk/news/business/rss.xml" },
        { "Politics", "https://feeds.bbci.co.uk/news/politics/rss.xml" },
        { "Health", "https://feeds.bbci.co.uk/news/health/rss.xml" },
        { "Education & Family", "https://feeds.bbci.co.uk/news/education/rss.xml" },
        { "Science & Environment", "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml" },
        { "Technology", "https://feeds.bbci.co.uk/news/technology/rss.xml" },
        { "Entertainment & Arts", "https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml" },
        { "Africa", "https://feeds.bbci.co.uk/news/world/africa/rss.xml" },
        { "Asia", "https://feeds.bbci.co.uk/news/world/asia/rss.xml" },
        { "Europe", "https://feeds.bbci.co.uk/news/world/europe/rss.xml" },
        { "Latin America", "https://feeds.bbci.co.uk/news/world/latin_america/rss.xml" },
        { "Middle East", "https://feeds.bbci.co.uk/news/world/middle_east/rss.xml" },
        { "US & Canada", "https://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml" },
        { "England", "https://feeds.bbci.co.uk/news/england/rss.xml" },
        { "Northern Ireland", "https://feeds.bbci.co.uk/news/northern_ireland/rss.xml" },
        { "Scotland", "https://feeds.bbci.co.uk/news/scotland/rss.xml" },
        { "Wales", "https://feeds.bbci.co.uk/news/wales/rss.xml" },
        { "Magazine", "https://feeds.bbci.co.uk/news/magazine/rss.xml" },
        { "Have your say", "https://feeds.bbci.co.uk/news/have_your_say/rss.xml" },
        { "Editors Blog", "https://www.bbc.co.uk/blogs/theeditors/rss.xml" },
        { "Edition - UK", "https://feeds.bbci.co.uk/news/rss.xml?edition=uk" },
        { "Edition - US & Canada", "https://feeds.bbci.co.uk/news/rss.xml?edition=us" },
        { "Edition - Rest of the world", "https://feeds.bbci.co.uk/news/rss.xml?edition=int" },
    } },
    { id = "guardian", title = "The Guardian", lang = "en", region = "world",
      base_url = "https://www.theguardian.com", filter_element = "article", categories = {
        { "Tin mới nhất", "/international/rss" },
        { "Opinion", "/commentisfree/rss" },
        { "Sport", "/sport/rss" },
        { "Culture", "/culture/rss" },
        { "Lifestyle", "/lifeandstyle/rss" },
        { "World news", "/world/rss" },
        { "US politics", "/us-news/us-politics/rss" },
        { "UK news", "/uk-news/rss" },
        { "Climate crisis", "/environment/climate-crisis/rss" },
        { "Middle East", "/world/middleeast/rss" },
        { "Ukraine", "/world/ukraine/rss" },
        { "Environment", "/environment/rss" },
        { "Science", "/science/rss" },
        { "Global development", "/global-development/rss" },
        { "Football", "/football/rss" },
        { "Tech", "/technology/rss" },
        { "Business", "/business/rss" },
        { "Obituaries", "/obituaries/rss" },
        { "The Guardian view", "/profile/editorial/rss" },
        { "Columnists", "/uk/columnists/rss" },
        { "Cartoons", "/tone/cartoons/rss" },
        { "Opinion videos", "/type/video+tone/comment/rss" },
        { "Letters", "/tone/letters/rss" },
        { "Cricket", "/sport/cricket/rss" },
        { "Rugby union", "/sport/rugby-union/rss" },
        { "Tennis", "/sport/tennis/rss" },
        { "Cycling", "/sport/cycling/rss" },
        { "F1", "/sport/formulaone/rss" },
        { "Golf", "/sport/golf/rss" },
        { "US sports", "/sport/us-sport/rss" },
        { "Books", "/books/rss" },
        { "Music", "/music/rss" },
        { "TV & radio", "/tv-and-radio/rss" },
        { "Art & design", "/artanddesign/rss" },
        { "Film", "/film/rss" },
        { "Games", "/games/rss" },
        { "Classical", "/music/classicalmusicandopera/rss" },
        { "Stage", "/stage/rss" },
        { "Fashion", "/fashion/rss" },
        { "Food", "/food/rss" },
        { "Recipes", "/tone/recipes/rss" },
        { "Love & sex", "/lifeandstyle/love-and-sex/rss" },
        { "Health & fitness", "/lifeandstyle/health-and-wellbeing/rss" },
        { "Home & garden", "/lifeandstyle/home-and-garden/rss" },
        { "Women", "/lifeandstyle/women/rss" },
        { "Men", "/lifeandstyle/men/rss" },
        { "Family", "/lifeandstyle/family/rss" },
        { "Travel", "/travel/rss" },
        { "Money", "/money/rss" },
        { "Video", "/video/rss" },
        { "Podcasts", "/podcasts/rss" },
        { "Pictures", "/inpictures/rss" },
        { "Crosswords", "/crosswords/rss" },
        { "Corrections", "/theguardian/series/corrections-and-clarifications/rss" },
    } },
    { id = "dw", title = "DW", lang = "en", region = "world",
      base_url = "https://rss.dw.com", filter_element = "main", categories = {
        { "Tất cả", "/rdf/rss-en-all" },
        { "Tin nổi bật", "/rdf/rss-en-top" },
        { "Đức", "/rdf/rss-en-ger" },
        { "Châu Á", "/rdf/rss-en-asia" },
        { "Kinh doanh", "/rdf/rss-en-bus" },
        { "Thể thao", "/rdf/rss-en-sports" },
        { "Văn hóa", "/rdf/rss-en-cul" },
        { "Môi trường", "/xml/rss_en_environment" },
        { "Khoa học", "/xml/rss_en_science" },
        { "Châu Âu", "/rdf/rss-en-eu" },
    } },
}
