-- All published RSS categories, including subcategories: https://thanhnien.vn/rss.html
-- Snapshot: 2026-09-04. Media feeds supply readable descriptions, not video playback.
return {
        { "Trang chủ", "/rss/home.rss" },
        { "Thời sự", "/rss/thoi-su.rss" },
        { "Thời sự / Pháp luật", "/rss/thoi-su/phap-luat.rss" },
        { "Thời sự / Dân sinh", "/rss/thoi-su/dan-sinh.rss" },
        { "Thời sự / Lao động - Việc làm", "/rss/thoi-su/lao-dong-viec-lam.rss" },
        { "Thời sự / Quyền được biết", "/rss/thoi-su/quyen-duoc-biet.rss" },
        { "Thời sự / Phóng sự / Điều tra", "/rss/thoi-su/phong-su--dieu-tra.rss" },
        { "Thời sự / Quốc phòng", "/rss/thoi-su/quoc-phong.rss" },
        { "Thời sự / Chống tin giả", "/rss/thoi-su/chong-tin-gia.rss" },
        { "Thời sự / Thành tựu y khoa", "/rss/thoi-su/thanh-tuu-y-khoa.rss" },
        { "Chính trị", "/rss/chinh-tri.rss" },
        { "Chính trị / Sự kiện", "/rss/chinh-tri/su-kien.rss" },
        { "Chính trị / Vươn mình trong kỷ nguyên mới", "/rss/chinh-tri/vuon-minh-trong-ky-nguyen-moi.rss" },
        { "Chính trị / Thời luận", "/rss/chinh-tri/thoi-luan.rss" },
        { "Chính trị / Đại hội XI Mặt trận tổ quốc Việt Nam", "/rss/chinh-tri/dai-hoi-xi-mat-tran-to-quoc-viet-nam.rss" },
        { "Chính trị / Ngày hội bầu cử", "/rss/chinh-tri/ngay-hoi-bau-cu.rss" },
        { "Chào ngày mới", "/rss/chao-ngay-moi.rss" },
        { "Thế giới", "/rss/the-gioi.rss" },
        { "Thế giới / Kinh tế thế giới", "/rss/the-gioi/kinh-te-the-gioi.rss" },
        { "Thế giới / Quân sự", "/rss/the-gioi/quan-su.rss" },
        { "Thế giới / Góc nhìn", "/rss/the-gioi/goc-nhin.rss" },
        { "Thế giới / Hồ sơ", "/rss/the-gioi/ho-so.rss" },
        { "Thế giới / Người Việt năm châu", "/rss/the-gioi/nguoi-viet-nam-chau.rss" },
        { "Thế giới / Chuyện lạ", "/rss/the-gioi/chuyen-la.rss" },
        { "Kinh tế", "/rss/kinh-te.rss" },
        { "Kinh tế / Kinh tế xanh", "/rss/kinh-te/kinh-te-xanh.rss" },
        { "Kinh tế / Chính sách - Phát triển", "/rss/kinh-te/chinh-sach-phat-trien.rss" },
        { "Kinh tế / Ngân hàng", "/rss/kinh-te/ngan-hang.rss" },
        { "Kinh tế / Chứng khoán", "/rss/kinh-te/chung-khoan.rss" },
        { "Kinh tế / Doanh nghiệp", "/rss/kinh-te/doanh-nghiep.rss" },
        { "Kinh tế / Khát vọng Việt Nam", "/rss/kinh-te/doanh-nhan.rss" },
        { "Kinh tế / Làm giàu", "/rss/kinh-te/lam-giau.rss" },
        { "Kinh tế / Địa ốc", "/rss/kinh-te/dia-oc.rss" },
        { "Đời sống", "/rss/doi-song.rss" },
        { "Đời sống / Thanh Niên và tôi", "/rss/doi-song/thanh-nien-va-toi.rss" },
        { "Đời sống / Tết yêu thương", "/rss/doi-song/tet-yeu-thuong.rss" },
        { "Đời sống / Người sống quanh ta", "/rss/doi-song/nguoi-song-quanh-ta.rss" },
        { "Đời sống / Gia đình", "/rss/doi-song/gia-dinh.rss" },
        { "Đời sống / Ẩm thực", "/rss/doi-song/am-thuc.rss" },
        { "Đời sống / Cộng đồng", "/rss/doi-song/cong-dong.rss" },
        { "Đời sống / Một nửa thế giới", "/rss/doi-song/mot-nua-the-gioi.rss" },
        { "Đời sống / Khát vọng năm rồng", "/rss/doi-song/khat-vong-nam-rong.rss" },
        { "Sức khỏe", "/rss/suc-khoe.rss" },
        { "Sức khỏe / Khỏe đẹp mỗi ngày", "/rss/suc-khoe/khoe-dep-moi-ngay.rss" },
        { "Sức khỏe / Làm đẹp", "/rss/suc-khoe/lam-dep.rss" },
        { "Sức khỏe / Giới tính", "/rss/suc-khoe/gioi-tinh.rss" },
        { "Sức khỏe / Y tế thông minh", "/rss/suc-khoe/y-te-thong-minh.rss" },
        { "Sức khỏe / Thẩm mỹ an toàn", "/rss/suc-khoe/tham-my-an-toan.rss" },
        { "Sức khỏe / Tin hay y tế", "/rss/suc-khoe/tin-hay-y-te.rss" },
        { "Giới trẻ", "/rss/gioi-tre.rss" },
        { "Giới trẻ / Sống - Yêu - Ăn - Chơi", "/rss/gioi-tre/song-yeu-an-choi.rss" },
        { "Giới trẻ / Tiếp sức gen Z mùa thi", "/rss/gioi-tre/tiep-suc-gen-z-mua-thi.rss" },
        { "Giới trẻ / Cơ hội nghề nghiệp", "/rss/gioi-tre/co-hoi-nghe-nghiep.rss" },
        { "Giới trẻ / Đoàn - Hội", "/rss/gioi-tre/doan-hoi.rss" },
        { "Giới trẻ / Kết nối", "/rss/gioi-tre/ket-noi.rss" },
        { "Giới trẻ / Khởi nghiệp", "/rss/gioi-tre/khoi-nghiep.rss" },
        { "Giới trẻ / Thế giới mạng", "/rss/gioi-tre/the-gioi-mang.rss" },
        { "Giới trẻ / Gương mặt trẻ", "/rss/gioi-tre/guong-mat-tre.rss" },
        { "Tiêu dùng thông minh", "/rss/tieu-dung-thong-minh.rss" },
        { "Tiêu dùng thông minh / Mới- Mới- Mới", "/rss/tieu-dung-thong-minh/moi-moi-moi.rss" },
        { "Tiêu dùng thông minh / Mua một chạm", "/rss/tieu-dung-thong-minh/mua-mot-cham.rss" },
        { "Tiêu dùng thông minh / Ở đâu rẻ?", "/rss/tieu-dung-thong-minh/o-dau-re.rss" },
        { "Tiêu dùng thông minh / Góc người tiêu dùng", "/rss/tieu-dung-thong-minh/goc-nguoi-tieu-dung.rss" },
        { "Giáo dục", "/rss/giao-duc.rss" },
        { "Giáo dục / Tuyển sinh", "/rss/giao-duc/tuyen-sinh.rss" },
        { "Giáo dục / Chọn nghề - Chọn trường", "/rss/giao-duc/chon-nghe-chon-truong.rss" },
        { "Giáo dục / Du học", "/rss/giao-duc/du-hoc.rss" },
        { "Giáo dục / Nhà trường", "/rss/giao-duc/nha-truong.rss" },
        { "Giáo dục / Phụ huynh", "/rss/giao-duc/phu-huynh.rss" },
        { "Giáo dục / Tra cứu điểm thi", "/rss/giao-duc/tra-cuu-diem-thi.rss" },
        { "Giáo dục / Ôn thi tốt nghiệp", "/rss/giao-duc/on-thi-tot-nghiep.rss" },
        { "Du lịch", "/rss/du-lich.rss" },
        { "Du lịch / Tin tức - Sự kiện", "/rss/du-lich/tin-tuc-su-kien.rss" },
        { "Du lịch / Chơi gì, ăn đâu, đi thế nào?", "/rss/du-lich/choi-gi-an-dau-di-the-nao.rss" },
        { "Du lịch / Bất động sản du lịch", "/rss/du-lich/bat-dong-san-du-lich.rss" },
        { "Du lịch / Câu chuyện du lịch", "/rss/du-lich/cau-chuyen-du-lich.rss" },
        { "Du lịch / Khám phá", "/rss/du-lich/kham-pha.rss" },
        { "Văn hóa", "/rss/van-hoa.rss" },
        { "Văn hóa / Sống đẹp", "/rss/van-hoa/song-dep.rss" },
        { "Văn hóa / Câu chuyện văn hóa", "/rss/van-hoa/cau-chuyen-van-hoa.rss" },
        { "Văn hóa / Khảo cứu", "/rss/van-hoa/khao-cuu.rss" },
        { "Văn hóa / Xem - Nghe", "/rss/van-hoa/xem-nghe.rss" },
        { "Văn hóa / Sách hay", "/rss/van-hoa/sach-hay.rss" },
        { "Văn hóa / Món ngon Hà Nội", "/rss/van-hoa/mon-ngon-ha-noi.rss" },
        { "Văn hóa / Nghĩa tình miền Tây", "/rss/van-hoa/nghia-tinh-mien-tay.rss" },
        { "Văn hóa / Hào khí miền Đông", "/rss/van-hoa/hao-khi-mien-dong.rss" },
        { "Giải trí", "/rss/giai-tri.rss" },
        { "Giải trí / Phim", "/rss/giai-tri/phim.rss" },
        { "Giải trí / Truyền hình", "/rss/giai-tri/truyen-hinh.rss" },
        { "Giải trí / Đời nghệ sĩ", "/rss/giai-tri/doi-nghe-si.rss" },
        { "Thể thao", "/rss/the-thao.rss" },
        { "Thể thao / World Cup 2026", "/rss/the-thao/world-cup-2026.rss" },
        { "Thể thao / Bóng đá Thanh Niên Sinh viên", "/rss/the-thao/bong-da-thanh-nien-sinh-vien.rss" },
        { "Thể thao / Bóng đá Việt Nam", "/rss/the-thao/bong-da-viet-nam.rss" },
        { "Thể thao / Bóng đá Quốc tế", "/rss/the-thao/bong-da-quoc-te.rss" },
        { "Thể thao / Thể thao & Cộng đồng", "/rss/the-thao/the-thao-cong-dong.rss" },
        { "Thể thao / Các môn khác", "/rss/the-thao/cac-mon-khac.rss" },
        { "Công nghệ", "/rss/cong-nghe.rss" },
        { "Công nghệ / Tin tức công nghệ", "/rss/cong-nghe/tin-tuc-cong-nghe.rss" },
        { "Công nghệ / Blockchain", "/rss/cong-nghe/blockchain.rss" },
        { "Công nghệ / Sản phẩm", "/rss/cong-nghe/san-pham.rss" },
        { "Công nghệ / Xu hướng - Chuyển đổi số", "/rss/cong-nghe/xu-huong-chuyen-doi-so.rss" },
        { "Công nghệ / Thủ thuật", "/rss/cong-nghe/thu-thuat.rss" },
        { "Công nghệ / Game", "/rss/cong-nghe/game.rss" },
        { "Xe", "/rss/xe.rss" },
        { "Xe / Thị trường", "/rss/xe/thi-truong.rss" },
        { "Xe / Xe xanh", "/rss/xe/xe-xanh.rss" },
        { "Xe / Đánh giá xe", "/rss/xe/danh-gia-xe.rss" },
        { "Xe / Tư vấn", "/rss/xe/tu-van.rss" },
        { "Xe / Video", "/rss/xe/video.rss" },
        { "Xe / Diễn đàn", "/rss/xe/dien-dan.rss" },
        { "Xe / Xe - Giao thông", "/rss/xe/xe-giao-thong.rss" },
        { "Thời trang trẻ", "/rss/thoi-trang-tre.rss" },
        { "Thời trang trẻ / Thời trang 24/7", "/rss/thoi-trang-tre/thoi-trang-247.rss" },
        { "Thời trang trẻ / Giữ dáng", "/rss/thoi-trang-tre/giu-dang.rss" },
        { "Thời trang trẻ / Thời trang nghề & nghiệp", "/rss/thoi-trang-tre/thoi-trang-nghe-nghiep.rss" },
        { "Thời trang trẻ / Tận hưởng", "/rss/thoi-trang-tre/tan-huong.rss" },
        { "Thời trang trẻ / Video", "/rss/thoi-trang-tre/video.rss" },
        { "Thời trang trẻ / Thư viện thời trang", "/rss/thoi-trang-tre/thu-vien-thoi-trang.rss" },
        { "Bạn đọc", "/rss/ban-doc.rss" },
        { "Bạn đọc / Lá thư tâm sự", "/rss/ban-doc/la-thu-tam-su.rss" },
        { "Bạn đọc / Từ đơn thư bạn đọc", "/rss/ban-doc/tu-don-thu-ban-doc.rss" },
        { "Bạn đọc / Hỏi và đáp", "/rss/ban-doc/hoi-va-dap.rss" },
        { "Bạn đọc / Bạn đọc viết", "/rss/ban-doc/ban-doc-viet.rss" },
        { "Bạn đọc / Cơ quan chưa trả lời bạn đọc", "/rss/ban-doc/co-quan-chua-tra-loi-ban-doc.rss" },
        { "Bạn đọc / Trả lời bạn đọc", "/rss/ban-doc/tra-loi-ban-doc.rss" },
        { "Bạn đọc / Lá lành đùm lá rách", "/rss/ban-doc/la-lanh-dum-la-rach.rss" },
        { "Bạn đọc / Tấm lòng vàng", "/rss/ban-doc/tam-long-vang.rss" },
        { "Video", "/rss/video.rss" },
        { "Video / Thời sự", "/rss/video/thoi-su.rss" },
        { "Video / Đời sống", "/rss/video/doi-song.rss" },
        { "Video / Giải trí", "/rss/video/giai-tri.rss" },
        { "Video / Giáo dục", "/rss/video/giao-duc.rss" },
        { "Video / Sức khỏe", "/rss/video/suc-khoe.rss" },
        { "Video / Thế giới", "/rss/video/the-gioi.rss" },
        { "Video / Trải nghiệm số", "/rss/video/trai-nghiem-so.rss" },
        { "Video / World Cup 2026", "/rss/video/world-cup-2026.rss" },
        { "Video / Thể thao", "/rss/video/the-thao.rss" },
        { "Video / Bí quyết ôn thi tốt nghiệp THPT", "/rss/video/bi-quyet-on-thi-tot-nghiep-thpt.rss" },
        { "Video / Phim ngắn Vietnamese", "/rss/video/phim-ngan-vietnamese.rss" },
        { "Video / Trực tuyến", "/rss/video/truc-tuyen.rss" },
        { "Video / Bóng đá Thanh Niên Sinh viên", "/rss/video/bong-da-thanh-nien-sinh-vien.rss" },
        { "Diễn đàn", "/rss/dien-dan.rss" },
        { "Diễn đàn / Văn hóa giao thông", "/rss/dien-dan/van-hoa-giao-thong.rss" },
        { "Podcast", "/rss/podcast.rss" },
        { "Podcast / GenZ", "/rss/podcast/genz.rss" },
        { "Podcast / Showbiz", "/rss/podcast/showbiz.rss" },
        { "Nhật ký Tết Việt", "/rss/nhat-ky-tet-viet.rss" },
        { "Magazine", "/rss/magazine.rss" },
        { "Cùng con đi tiếp cuộc đời", "/rss/cung-con-di-tiep-cuoc-doi.rss" },
        { "Bạn cần biết", "/rss/ban-can-biet.rss" },
        { "Bạn cần biết / Miền Bắc", "/rss/ban-can-biet/mien-bac.rss" },
        { "Bạn cần biết / Miền Nam", "/rss/ban-can-biet/mien-nam.rss" },
        { "Bạn cần biết / Miền Trung", "/rss/ban-can-biet/mien-trung.rss" },
        { "Bạn cần biết / Sản phẩm", "/rss/ban-can-biet/san-pham.rss" },
        { "Bạn cần biết / Dịch vụ", "/rss/ban-can-biet/dich-vu.rss" },
        { "Bạn cần biết / Giải thưởng", "/rss/ban-can-biet/giai-thuong.rss" },
        { "Bạn cần biết / Thông báo", "/rss/ban-can-biet/thong-bao.rss" },
        { "Bạn cần biết / Giải trí", "/rss/ban-can-biet/giai-tri.rss" },
        { "Bạn cần biết / Tuyển dụng", "/rss/ban-can-biet/tuyen-dung.rss" },
        { "Blog phóng viên", "/rss/blog-phong-vien.rss" },
        { "Tôi viết", "/rss/toi-viet.rss" },
        { "TNO", "/rss/tno.rss" },
        { "Tin 24h", "/rss/tin-24h.rss" },
        { "Tin thị trường", "/rss/thi-truong.rss" },
        { "Tin nhanh 360", "/rss/tin-nhanh-360.rss" },
}
